[tool.black]
line-length = 100
target-version = ["py310"]
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 100
force_single_line = true
src_paths = ["frinx_python_sdk"]

[tool.mypy]
python_version = "3.10"

mypy_path = [
    "frinx_python_sdk"
]
exclude = [
    "frinx_conductor_worker",
    "standalone_main.py",
    "main.py",
    "frinx_python_sdk/test/*",
    "frinx_python_sdk/src/frinx/main.py",
    "frinx_python_sdk/src/frinx/client",
]

explicit_package_bases = true
strict = true
pretty = true
ignore_missing_imports = true
disallow_untyped_defs= true
disallow_subclassing_any = false

[tool.pytest.ini_options]
pythonpath = "frinx_python_sdk/src"
