[tool.black]
line-length = 100
target-version = ["py310"]
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 100
force_single_line = true
src_paths = ["topology_discovery"]
