name: pr-check

on:
  pull_request:
    branches: [master]
    
  workflow_dispatch:

jobs:
  format-test:
    name: Format check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Black check python files
        uses: psf/black@stable
        with:
          version: "22.3.0"

      - name: Isort check python files
        uses: isort/isort-action@v1.0.0
        with:
          isort-version: "5.10.1"

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false
