name: pr-check

on:
  pull_request:
    branches: [master]
    
  workflow_dispatch:

jobs:
  format-test:
    name: Format & Unit tests check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Black check python files
        uses: psf/black@stable

      - name: Isort check python files
        uses: isort/isort-action@v1.0.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install -r frinx_python_sdk/requirements.txt 


      - name: Test with pytest
        run: |
          pytest -v --ignore=system_tests

#       - name: Install mypy
#         run: pip install mypy

#       - name: Run mypy 
#         run: mypy ./frinx_python_sdk

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false
